### ISSUE TITLE
Activity and their input

### ISSUE THREAD

**Issue by davidstarkcab** [microsoft/DurableFunctionsMonitor#1] opened 2021-12-03 09:50 UTC
Hello!

Big thanks for this awesome project, keep it up!

Today you can see the result of an activity, but I wonder if it’s possible to view the input of an activity?

Thanks in advance!

**Comment by scale-tone** [comment] 2021-12-03 23:10
@davidstarkcab , the reason why today DfMon cannot show you activity inputs is because Durable Task Framework doesn't write them to *History table. And it is a good question why it doesn't. 

@cgillum, looks like `TaskScheduled` events always have their `Input` field set to null (and [you mentioned that they shouldn't](https://github.com/Azure/durabletask/tree/main/src/DurableTask.Core/History#durable-task-framework-history-events)). Is that a bug?

**Comment by cgillum** [comment] 2021-12-04 04:02
This is not a bug. It’s always been this way, since before I got involved in the project. It’s set only in the queue message’s copy of the task scheduled event. I assume this was an optimization to save storage costs since the history replay doesn’t require the inputs.

The exception to this is the newer MSSQL backend, which does keep inputs in the DB. I can update that README to clarify.

**Comment by davidstarkcab** [comment] 2021-12-06 06:43
@cgillum Is it possible we can have a configuration for this in the future for us using blob storage? I can understand that you don´t want this per default active for billing purposes, but for us it would be great to see what the input was for error searching. I mean it would be great to see this in Durable Function Monitor instead we have to log this information to Application Insights.

**Comment by cgillum** [comment] 2021-12-06 17:48
@davidstarkcab sure, we can look into this. Would you mind opening a feature proposal [here](https://github.com/Azure/azure-functions-durable-extension/issues/new?assignees=&labels=&template=feature_request.md&title=) and including a reference to this discussion?

**Comment by davidstarkcab** [comment] 2021-12-07 07:42
@cgillum I have now created the feature proposal, please fel free to add an comment if i have missed or missunderstod anything.

**Comment by scale-tone** [comment] 2022-11-23 20:40
@davidstarkcab , so [your request](https://github.com/Azure/azure-functions-durable-extension/issues/2032) has just been completed in [Durable Functions v2.9](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.9.0), which means that it should now just start working in DfMon.

Can you please confirm?

**Comment by scale-tone** [comment] 2023-02-26 11:14
Let's assume it works now. So closing this.
Feel free to open another issue if something does not work.

**Closed by scale-tone** 2023-02-26 11:14 UTC
Labels: enhancement
